### ISSUE TITLE
I get an error when i start with npm run build 

### ISSUE THREAD

**Issue by Bouali-Ramzi** [lwojcik/eleventy-template-bliss#121]
Hi , when i try to build the project it seems like the tags doesn't render correctly this happened after i added an img element inside single-post-excerpt.njk 

img
        src="{{ post.data.image.src }}"
        alt="{{ post.data.imageAlt.alt }}"
        class="snippet__image"
    

 
![tag-error](https://github.com/lwojcik/eleventy-template-bliss/assets/92471905/70865914-7561-4afb-9496-ee09d649767d)

**Comment by lwojcik** [comment]
Hi @Bouali-Ramzi! 

Sorry I kept you waiting.

The fix for this is in #147 and it will be in v2.6.0.
