### ISSUE TITLE
Post description will display footnotes as text instead of markdown syntax

### ISSUE THREAD

**Issue by mark-pitblado** [lwojcik/eleventy-template-bliss#122]
Minor issue, but I noticed that footnote syntax will display in the truncated description (notice the [1] following 'catppuccin').

![image](https://github.com/lwojcik/eleventy-template-bliss/assets/86988982/4f413ac8-ba06-4bc3-ad3e-8a0973da82ad)

If you like, I can work to submit a fix for this, I just cannot promise anything in terms of timeline.

**Comment by mark-pitblado** [comment]
Actually, the more I think about this, I guess this is actually the proper behaviour? It doesn't make practical sense for footnotes to be displayed in an excerpt, however the fact that the word has a reference is information that would appear in something like a printed book. I think in the json excerpt it may create a funny link because it will try to reference a footnote that isn't there.

If you think that the current state is how it should work than feel free to close!

**Comment by lwojcik** [comment]
Hi @mark-pitblado, 

Thanks for reaching out!

That was my personal choice and it was about aesthetics - I wanted the front page to look a little cleaner and display extra formatting only with full posts.

I'm not closing this yet though - I'll see if HTML formatting can be safely enabled for post excerpts and implement it as an optional feature if the answer is yes.

**Comment by lwojcik** [comment]
Okay, I had a look at this and I will not be changing that for now.

I know those footnotes in the excerpts look funny, but I have no idea how to change it in a way they remain usable. And I can't think of a way to remove them entirely from the excerpts.

But I might be open to review a pull request tackling this problem in some smart way.

**Comment by mark-pitblado** [comment]
I agree, after further reflection I also don't know how it would be handled differently.
