### ISSUE TITLE
Fabform

### ISSUE THREAD

**Issue by Irishgeoff11** [lwojcik/eleventy-template-bliss#55]
Can you add a fabform.io contact form to this theme

**Comment by lwojcik** [comment]
Thanks for reaching out. I can see you're trying to get people interested in your product and I appreciate you are reasonably open about that.

I currently have no plans of extending the theme with a contact form.

If any of the users of my theme expresses interest in having one, I'll be happy to provide them with instructions and recommend your tool alongside other similar ones.
