### ISSUE TITLE
CSS file not found

### ISSUE THREAD

**Issue by adevtobe** [lwojcik/eleventy-template-bliss#81]
First off, I think you theme looks great and I'm excited to use it for my blog however I ran into an issue. After forking it I ran `npm install` and then `npx @11ty/eleventy --serve`. When going to `localhost:8080` in the browser though, it was evident no CSS was being applied and the console confirmed this. Did I miss a step?

![image](https://github.com/lwojcik/eleventy-template-bliss/assets/155280981/9959ea00-782e-40a0-bec3-25e67e2eaa5b)

![image](https://github.com/lwojcik/eleventy-template-bliss/assets/155280981/00fc17d6-2065-47d6-91c5-94ec165c4578)

**Comment by Nasirahamad88** [comment]
import your CSS file correctly.

**Comment by lwojcik** [comment]
Hi @adevtobe, thanks for reaching out!

`npx @11ty/eleventy --serve` only starts the project but it doesn't build the CSS stylesheet out of SASS source files.

Use `npm start` or `npm run dev`.

Or, if you want to stick to using `npx @11ty/eleventy --serve`, in a separate terminal run `npm run build:sass` (once) or `npm run watch watch:sass` (if you want to edit the CSS).

Let me know if you have any more questions!

**Comment by adevtobe** [comment]
Thanks @lwojcik! I'm moving over from Hexo and this is my first time using eleventy so my only experience so far is following their docs. I should have checked the `package.json`. 

Only other question I have is, is this something that will run fine on Github pages? I wasn't sure if any of the features require an actual backend.

**Comment by lwojcik** [comment]
> Only other question I have is, is this something that will run fine on Github pages? I wasn't sure if any of the features require an actual backend.

Never tried it but quick googling suggests it should be possible:

- https://maarten.be/blog/20220730/how-to-deploy-your-eleventy-website-to-github-pages-with-github-actions/
- https://quinndombrowski.com/blog/2022/05/07/hosting-eleventy-on-github-pages/
