### ISSUE TITLE
"Error: EBUSY: resource busy or locked" in Powershell 7

### ISSUE THREAD

**Issue by lwojcik** [lwojcik/eleventy-template-bliss#91]
While starting the project with `npm run dev` in Powershell 7 on Windows 10, the following error is displayed and the command fails:

![Screenshot 2024-02-14 at 22 33 14](https://github.com/lwojcik/eleventy-template-bliss/assets/1711174/46b08998-eee2-4d7c-8cd0-73156d2a337e)

Until the issue is solved, the following workarounds seem to work:

- Use older version of Powershell or [git on Windows](https://gitforwindows.org/)
- open separate Powershell 7 window and run `npm run watch:eleventy` directly

**Comment by joel-lbth** [comment]
i use your template (and very nice it is too) and sometimes encounter the same "EBUSY: resource busy or locked" scenario, and it is always to do with the favicon, though it is also intermittent. it happens in git bash as well as powershell in windows 10, and also happens with npm run build - it usually goes away after a retry. not sure what to add really as it's not happening currently!

**Comment by Bouali-Ramzi** [comment]
I replaced this nunjucks code `{%- favicons 'assets/favicon.svg', appleIconPadding=0 -%}` in favicons.njk with this metadata output in from _site
`<link rel="icon" href="/favicon.ico" sizes="any" />
<link rel="icon" href="/favicon.svg" type="image/svg+xml" />
`
and it fixed it for me

**Comment by Bouali-Ramzi** [comment]
I replaced this nunjucks code {%- favicons 'assets/favicon.svg', appleIconPadding=0 -%} in favicons.njk with this metadata output in from _site
<link rel="icon" href="/favicon.ico" sizes="any" />
<link rel="icon" href="/favicon.svg" type="image/svg+xml" />

 and it fixed it for me

**Comment by lwojcik** [comment]
Since this issue has to do with an unresolved bug in an external plugin and I can't put enough time to diagnose and fix it, starting from v2.4.0 Bliss no longer ships with automatic favicon generation.

If you liked the feature, feel free to reimplement it on your own - consult [change history from this PR](https://github.com/lwojcik/eleventy-template-bliss/pull/99) to get it back.

**Comment by Bouali-Ramzi** [comment]
Thank you

Le sam. 2 mars 2024 à 00:43, Łukasz Wójcik ***@***.***> a
écrit :
